### PR TITLE
Add speakers section to website

### PR DESCRIPTION
**Pull request by doggodoge**
Hey! I heard that you folks may be in need of a speakers section, so have tried my hand at one. Feedback more than welcome 😁

## Description

This PR adds a speakers section to the SISTEM 2023 website. Speakers can be added by including them in the `./data/speakers.js` file.

## Changes

- Add new `Speakers.jsx` component.
- Add `speakers.js` file for adding new speakers.
- Add new speakers hyperlink to the `<Navbar />` component.
- Add new `/speakers` route.

## Todo

- [x] Add actual speakers to the `speakers.js` file.
- [x] Improve the strange looking `flex-grow`, perhaps use a grid instead.
- [x] Add linkedin link.
- [x] Add `prettierrc.json` config so formatting doesn't change your quotes (sorry about that).

### CODE REVIEW

**Comment by doggodoge** [comment]
I've changed the state to ready for review to see if cloudflare pages will build the branch from a fork. Still WIP.

**Comment by doggodoge** [comment]
Apologies, that's not something it supports. Changing it back to draft state

**Comment by doggodoge** [comment]
Only thing remaining is to get real speakers into the `speakers.js` file.

**Comment by ParadauxIO** [comment]
> I've changed the state to ready for review to see if cloudflare pages will build the branch from a fork. Still WIP.

That's weird it should have, I've probably misconfigured it at the org level -- No worries just request a review when you're ready and i'll take a look, thanks for your help so far!

**Comment by doggodoge** [comment]
> > I've changed the state to ready for review to see if cloudflare pages will build the branch from a fork. Still WIP.
> 
> That's weird it should have, I've probably misconfigured it at the org level -- No worries just request a review when you're ready and i'll take a look, thanks for your help so far!

From their [Known Issues](https://developers.cloudflare.com/pages/platform/known-issues/) page:

> Commits/PRs from forked repositories will not create a preview. Support for this will come in the future.

That's unfortunate :(

**Comment by doggodoge** [comment]
I've now added the speakers for the conference, and tested the responsive design on a big 1440p monitor, an iPad, and an iPhone Mini. This should be good to go! Pending review of course. 🙂

**Pull request merged**
